services:
  pocketbase:
    container_name: fantan-pb-dev
    # restart: unless-stopped
    image: ghcr.io/muchobien/pocketbase:0.22.20
    environment:
      - TURNSTILE_SECRET_KEY=1x0000000000000000000000000000000AA
    volumes:
      - ./pb_data:/pb_data
      - ./pb_hooks:/pb_hooks
      - ./pb_migrations:/pb_migrations
    ports:
      - 8090:8090
