services:
  pocketbase:
    container_name: fantan-pb-dev
    # restart: unless-stopped
    image: ghcr.io/muchobien/pocketbase:0.22.20
    volumes:
      - ./pb_data:/pb_data
    ports:
      - 8090:8090
